version: '3'

services:
  
  zookeeper:
    image: zookeeper:3.6.2
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "flight_delay_classification_request:1:1"
      KAFKA_LISTENERS: OUTSIDE://kafka:29092,INSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: OUTSIDE:PLAINTEXT,INSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: OUTSIDE
      KAFKA_ADVERTISED_LISTENERS: OUTSIDE://kafka:29092,INSIDE://localhost:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mongodb:
    image: mongo:4.2
    restart: always
    ports:
      - "27017:27017"
  
  mongo_seed:
    build: ./mongo_seed
    links:
      - mongodb
    volumes:
      - volume_spark:/practica_big_data_2019

  spark:
    build: ./spark
    user: root
    volumes: 
      - volume_spark:/opt/bitnami/spark/work/practica_big_data_2019
    links:
      - kafka
      - mongodb

  predict_flask:
    build: ./predict_flask
    volumes:
      - volume_spark:/practica_big_data_2019
    links:
      - kafka
      - mongodb
    ports:
      - "5000:5000"

volumes:
  volume_spark:
    driver: local


  
  
  



